package es.in2.trustregistry.snapshot.infrastructure.adapter;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.JWSObject;
import com.nimbusds.jose.crypto.ECDSAVerifier;
import com.nimbusds.jose.jwk.Curve;
import com.nimbusds.jose.jwk.ECKey;
import com.nimbusds.jose.jwk.gen.ECKeyGenerator;
import es.in2.trustregistry.snapshot.domain.model.PublicVerificationKey;
import es.in2.trustregistry.snapshot.domain.model.TrustProfile;
import es.in2.trustregistry.snapshot.domain.model.TrustSnapshot;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.text.ParseException;
import java.time.Instant;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for {@link JwsSnapshotSigner} after task 12's rewrite: the signing key is now
 * constructor-injected (as {@link KeystoreSnapshotSigningKeyProvider} would supply it) rather
 * than generated by the class itself — {@code generateEphemeralKey()} no longer exists.
 *
 * <p>Uses a locally-generated {@link ECKey} rather than task 11's keystore fixture: this test
 * only needs "some" valid EC key pair, not a specific one loaded from a file, and generating
 * one in-memory keeps this test independent of the keystore-loading path already covered by
 * {@code KeystoreSnapshotSigningKeyProviderTest}.
 */
class JwsSnapshotSignerTest {

    private static final TrustSnapshot SNAPSHOT = new TrustSnapshot(
            "sandbox", 7L, Instant.parse("2026-08-25T10:00:00Z"), 86400, List.of(), List.of(),
            TrustProfile.PRODUCTION, false, Instant.parse("2026-08-25T09:00:00Z"));

    private ECKey signingKey;
    private JwsSnapshotSigner signer;

    @BeforeEach
    void setUp() throws JOSEException {
        ObjectMapper objectMapper = new ObjectMapper()
                .registerModule(new JavaTimeModule())
                .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        signingKey = new ECKeyGenerator(Curve.P_256).keyID("snapshot-signing").generate();
        signer = new JwsSnapshotSigner(objectMapper, signingKey);
    }

    @Test
    void sign_ValidSnapshot_ProducesAJwsVerifiableWithThePublishedPublicKey() throws ParseException, JOSEException {
        // Act
        String serialized = signer.sign(SNAPSHOT);

        // Assert: this is the whole point of the snapshot — a consumer with only the
        // public key, and no connectivity to the registry, must be able to verify it.
        JWSObject jws = JWSObject.parse(serialized);
        assertThat(jws.verify(new ECDSAVerifier(signer.publicKey()))).isTrue();
    }

    @Test
    void sign_ValidSnapshot_CarriesTheKeyIdAndTheSnapshotMediaType() throws ParseException {
        // Act
        JWSObject jws = JWSObject.parse(signer.sign(SNAPSHOT));

        // Assert: the kid is whatever the injected key carries (the keystore alias in
        // production), never a value this class invents.
        assertThat(jws.getHeader().getKeyID()).isEqualTo(signingKey.getKeyID());
        assertThat(jws.getHeader().getType().toString()).isEqualTo("trust-snapshot+jwt");
    }

    @Test
    void sign_ValidSnapshot_PayloadCarriesTheTenantAndTheVersion() throws ParseException {
        // Act
        JWSObject jws = JWSObject.parse(signer.sign(SNAPSHOT));

        // Assert
        assertThat(jws.getPayload().toJSONObject())
                .containsEntry("tenantId", "sandbox")
                .containsEntry("version", 7L);
    }

    @Test
    void publicKey_AfterConstruction_DoesNotExposeThePrivatePart() {
        // Act & Assert: the signing material must never leave the service.
        assertThat(signer.publicKey().isPrivate()).isFalse();
    }

    @Test
    void verificationMaterial_Always_ReturnsExactlyThePublicKey() {
        // Act
        List<PublicVerificationKey> material = signer.verificationMaterial();

        // Assert: AC-02 — a consumer needs exactly this to verify offline; NFR-S-228-01 — the
        // returned type has no field a private scalar could occupy, but the value itself is
        // also checked here to catch a coordinate mismatch, not just a private leak.
        ECKey publicKey = signingKey.toPublicJWK();
        assertThat(material).containsExactly(new PublicVerificationKey(
                publicKey.getKeyID(), publicKey.getCurve().getName(),
                publicKey.getX().toString(), publicKey.getY().toString()));
    }
}
