import eu.europa.esig.dss.enumerations.Indication;
import eu.europa.esig.dss.model.DSSDocument;
import eu.europa.esig.dss.model.FileDocument;
import eu.europa.esig.dss.model.x509.CertificateToken;
import eu.europa.esig.dss.spi.x509.CommonCertificateSource;
import eu.europa.esig.dss.token.DSSPrivateKeyEntry;
import eu.europa.esig.dss.token.Pkcs12SignatureToken;
import eu.europa.esig.dss.tsl.validation.TLValidatorTask;
import eu.europa.esig.dss.tsl.validation.ValidationResult;

import java.io.IOException;
import java.nio.file.Path;
import java.security.KeyStore;
import java.util.List;

/**
 * Smoke-checks every fixture generated by {@link GenerateTslFixtures} (task 13) using DSS's
 * own {@link TLValidatorTask} — the same class {@code TLValidatorTaskTest} in
 * {@code dss-tsl-validation} uses to assert a real EU LOTL's signature. Not a JUnit test:
 * task 15 owns the permanent container-based integration test. This is a one-off,
 * fail-fast confirmation that regeneration produced fixtures DSS itself will actually accept
 * or reject as intended, so a broken fixture is caught here rather than discovered later
 * while writing task 15's container test.
 *
 * <p>Invoked by {@code regenerate-fixtures.sh} right after generation.
 */
public final class VerifyTslFixtures {

    private static final Path FIXTURES_DIR = Path.of("src/test/resources/fixtures/tsl");
    private static final Path KEYSTORE_PATH = FIXTURES_DIR.resolve("keystore/tsl-test-signing-keystore.p12");
    private static final char[] KEYSTORE_PASSWORD = "tsl-test-password".toCharArray();
    private static final String CA_ALIAS = "tsl-test-ca";

    private static final List<String> EXPECTED_VALID = List.of(
            "lotl-valid.xml",
            "lotl-stale-next-update.xml",
            "lotl-valid-mixed.xml",
            "tl-national-a-valid.xml",
            "tl-national-b-valid.xml",
            "tl-national-stale-next-update.xml",
            "tl-national-three-statuses.xml"
    );

    private static final List<String> EXPECTED_TAMPERED = List.of(
            "lotl-tampered.xml",
            "tl-national-tampered.xml"
    );

    public static void main(String[] args) throws IOException {
        KeyStore.PasswordProtection password = new KeyStore.PasswordProtection(KEYSTORE_PASSWORD);
        boolean allPassed = true;
        try (Pkcs12SignatureToken signingToken = new Pkcs12SignatureToken(KEYSTORE_PATH.toFile(), password)) {
            DSSPrivateKeyEntry caKey = signingToken.getKey(CA_ALIAS, password);
            CertificateToken caCertificate = caKey.getCertificate();
            CommonCertificateSource certificateSource = new CommonCertificateSource();
            certificateSource.addCertificate(caCertificate);

            for (String fileName : EXPECTED_VALID) {
                allPassed &= check(fileName, certificateSource, Indication.TOTAL_PASSED);
            }
            for (String fileName : EXPECTED_TAMPERED) {
                allPassed &= check(fileName, certificateSource, Indication.TOTAL_FAILED);
            }
        }

        if (!allPassed) {
            System.err.println("One or more fixtures did not validate as expected.");
            System.exit(1);
        }
        System.out.println("All fixtures validated as expected.");
    }

    private static boolean check(String fileName, CommonCertificateSource certificateSource,
                                  Indication expectedIndication) {
        DSSDocument trustedList = new FileDocument(FIXTURES_DIR.resolve(fileName).toFile());
        TLValidatorTask task = new TLValidatorTask(trustedList, certificateSource);
        ValidationResult result = task.get();
        boolean matches = expectedIndication == result.getIndication();
        String outcome = matches ? "OK" : "MISMATCH";
        System.out.printf("[%s] %s -> expected=%s actual=%s%s%n",
                outcome, fileName, expectedIndication, result.getIndication(),
                result.getSubIndication() != null ? " (" + result.getSubIndication() + ")" : "");
        return matches;
    }
}
